#!/usr/bin/env python
import argparse
import logging
from main import main

if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser(
        description='check all links in spec file types in the directory')
    arg_parser.add_argument('-crash', '--crash', required=False,
                            help='crash if any broken links are found',
                            default=False)
    arg_parser.add_argument('-config_path', '--config_path', required=False,
                            help='path to config file',
                            default="config.yaml")
    arg_parser.add_argument('-directory', '--directory', required=False,
                            help='directory for pytest url to check')
    args = vars(arg_parser.parse_args())
    main(args['crash'], args['directory'], args['config_path'])
